---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ned300889/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    no_log: false
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
